### ISSUE TITLE
Support Different Fonts

### ISSUE THREAD

**Issue by connerbw** [pressbooks/pb-mathjax#11]
Add `&font=X` param to URL. Let the user change the font to use for rendering the mathematics. The default is: `font: "TeX"`

The possible values are TeX, STIX-Web, Asana-Math, Neo-Euler, Gyre-Pagella, Gyre-Termes and Latin-Modern. Note that not all mathematical characters are available in all fonts (e.g., Neo-Euler does not include italic characters), so some mathematics may work better in some fonts than in others. The STIX-Web font is the most complete.

Source: http://docs.mathjax.org/en/latest/options/output-processors/SVG.html#configure-svg

**Comment by mcgratay** [comment]
STIX-Web font has trouble rendering LaTeX in PDF format and winds up turning a lot of characters into question marks. 
![Screen Shot 2019-06-28 at 3 22 43 PM](https://user-images.githubusercontent.com/39064028/60366126-95eed400-99b8-11e9-8a70-01e40998bdf5.png)
[StixLaTeXOnly.pdf](https://github.com/pressbooks/pb-mathjax/files/3340545/StixLaTeXOnly.pdf)

https://testbook2948593.textopress.com/

**Comment by connerbw** [comment]
I posted a question in the PrinceXML forums about the STIX-Web font troubles. Hopefully someone from over there can help explain this. 

https://www.princexml.com/forum/topic/4183/mathjax-svg-files-as-img-tags-can-anyone-help-me-with-css

**Comment by connerbw** [comment]
I've been running tests and this may be the issue:

https://github.com/mathjax/MathJax/issues/2035

Ie.

> SVG - Unknown character: U+1D461 in STIXMathJax_Main-bold-italic,STIXMathJax_Normal-bold-italic,STIXMathJax_Script-bold-italic,STIXMathJax_DoubleStruck-bold-italic,STIXMathJax_SansSerif-bold-italic,STIXMathJax_Latin-bold-italic,STIXMathJax_Alphabets-bold-italic,STIXMathJax_Marks-bold-italic,STIXMathJax_Shapes-bold-italic,STIXMathJax_Misc-bold-italic,STIXMathJax_Variants-bold-italic,STIXMathJax_Size1

**Comment by pkra** [comment]
> I've been running tests and this may be the issue:

Just FYI "unknown character" means that MathJax did not find a path matching the unicode point (i.e., didn't find a glyph in the original font); in those cases it falls back to an SVG text element with Unicode in it (which is not ideal since fons won't match); this may very well be a problem for Prince but it's fairly normal for SVGs to have `<text>` elements.

**Comment by connerbw** [comment]
>  it's fairly normal for SVGs to have <text> elements

Thanks @pkra. The SVG's with text nodes render fine in the browser:

![image](https://user-images.githubusercontent.com/812192/60463961-507e1100-9c1b-11e9-84c9-6a7c78e06027.png)

As I type, the problem can be split into 3 distinct issues:

1. I expect Prince to behave like a browser. Prince should render text nodes in SVG files like how a browser does. Hopefully the forum thread leads to a solution.
1. Can't find U+1D461 in Stix-Web. This gets fixed if I apply either of the patches from https://github.com/mathjax/MathJax/issues/2035
1. Pb-mathjax, using mathjax-node, generates a PNG from the SVG using [Sharp](https://github.com/lovell/sharp).  When a font can't be found in #2, it affects this process:

![image](https://user-images.githubusercontent.com/812192/60464049-815e4600-9c1b-11e9-8623-26085b18b331.png)

(and goes away with either https://github.com/mathjax/MathJax/issues/2035 patch:)

![image](https://user-images.githubusercontent.com/812192/60464274-1103f480-9c1c-11e9-82b3-f085e9af615d.png)

**Comment by connerbw** [comment]
PS: Here's the text case:

```latex
\boldsymbol{\Delta{p}_1=F_1\Delta{t},}
```
