### ISSUE TITLE
git clone did not work with the command given

### ISSUE THREAD

**Issue by thomasdumm** [pressbooks/pb-mathjax#14]
This did not work:
git clone git@github.com:pressbooks/pb-mathjax.git

This worked:
git clone https://github.com/pressbooks/pb-mathjax.git

**Comment by dac514** [comment]
https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account

**Comment by dac514** [comment]
Also see:
https://help.github.com/en/articles/which-remote-url-should-i-use
