### ISSUE TITLE
MathML & visual editor research spike [don't break]

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pb-mathjax#7]
Switching between the visual and text editors strips out semantic MathML tags. In a timeboxed way, investigate whether we can stop this from happening, or report the issue upstream to be fixed.

**Comment by connerbw** [comment]
Switching between the visual and text editors breaks MathML tags
We can stop this from happening by forcing the MathML into one line without any returns

**Comment by mcgratay** [comment]
√ MathML written in hierarchy instead of in one line without breaks now does display correctly. 
X Semantic tags are still stripped out when you switch between the visual and text editors. See image for before and after 

![Screen Shot 2019-06-26 at 2 20 00 PM](https://user-images.githubusercontent.com/39064028/60206186-f1865980-9820-11e9-837e-6654fa04ded8.png)

**Comment by connerbw** [comment]
Added "Content Markup" to allowed tags.

**Comment by mcgratay** [comment]
The editor no long strips out content markup/semantic tags when you switch from text to visual and back. However, semantic tags (which still exist) will not be visible in the visual editor as a rendered equation like presentational tags are. 

See: https://testbook2948593.textopress.com/wp/wp-admin/post.php?post=188&action=edit
![Screen Shot 2019-06-28 at 3 51 35 PM](https://user-images.githubusercontent.com/39064028/60367613-9e490e00-99bc-11e9-980e-15cba49c677c.png)

![Screen Shot 2019-06-28 at 3 48 58 PM](https://user-images.githubusercontent.com/39064028/60367569-82456c80-99bc-11e9-989e-651e7e2b6017.png)

**Comment by connerbw** [comment]
@taylor I think that's the expected behaviour for web browsers:

> The term presentation markup is used to describe the layout structure of mathematical notation whereas content markup provides the underlying mathematical meaning and is not supposed to be rendered by the MathML parser (see bug 276028). 

https://developer.mozilla.org/en-US/docs/Web/MathML/Element
https://bugzilla.mozilla.org/show_bug.cgi?id=276028

**Comment by mcgratay** [comment]
👍 

Also note that I forgot to wrap that last presentational one in '<math>'
