### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pb-mathjax#75]
Bump Node requirements and ensure the tool works as expected in a supported version of Node.js. See https://pressbooks.community/t/latex-recommendation/2142

**Comment by arzola** [comment]
Our current implementation uses Mathjax-node that now could be replaced by the latest Mathjax 3 library https://www.npmjs.com/package/mathjax that works on browser and also as a node module

* We should replace Mathax-node with Mathjax 3 and refactor with new API
* Upgrade ClaudiaJs
* Upgrade aws-serverless-express with https://github.com/vendia/serverless-express
* Upgrade express server

**Comment by SteelWagstaff** [comment]
Closing in favour of #86
