### ISSUE TITLE
MathML comments double hyphen in webbook bug

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pb-mathjax#8]
See Taylor's testing notes: https://docs.google.com/document/d/1JaPOKq-yHjJL3cBdmVcj8yh3RGAVt-4vq9F9C4mJ8gI/edit#bookmark=id.v8fygaoi6bij

**Comment by connerbw** [comment]
Test case:

`<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow> <mi>x</mi><mo>=</mo><mfrac><mrow><mo form="prefix">−<!-- minus sign --></mo><mi>b</mi><mo>±<!-- &PlusMinus; --></mo><msqrt><msup><mi>b</mi><mn>2</mn></msup><mo>−<!-- minus sign --></mo><mn>4</mn><mo>⁢<!-- &InvisibleTimes; --></mo><mi>a</mi><mo>⁢<!-- &InvisibleTimes; --></mo><mi>c</mi></msqrt></mrow><mrow><mn>2</mn><mo>⁢<!-- &InvisibleTimes; --></mo><mi>a</mi></mrow></mfrac></mrow></math>`

Webbook turns it into:

`<math xmlns="http://www.w3.org/1998/Math/MathML"><mrow> <mi>x</mi><mo>=</mo><mfrac><mrow><mo form="prefix">−<!- minus sign -->b±<!-- &PlusMinus; -->b2−<!-- minus sign -->4⁢<!-- &InvisibleTimes; -->a⁢<!-- &InvisibleTimes; -->c2⁢<!-- &InvisibleTimes; -->a --&gt;`

😕

**Comment by pkra** [comment]
You can disable the hints in MathJax, cf. http://docs.mathjax.org/en/latest/options/hub.html?highlight=texhints.

**Comment by connerbw** [comment]
The problem was htmlLawed mangling mixed markup.  ([More info.](http://www.bioinformatics.org/phplabware/internal_utilities/htmLawed/htmLawed_README.htm#s3.9))

Fixed in: https://github.com/pressbooks/pressbooks/commit/38aa0190252b752a9c010d27584eb2192882c9f4

**Comment by mcgratay** [comment]
Resolved.
