### ISSUE TITLE
MathML w/ semantic tags fail in exports

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pb-mathjax#9]
See Taylor's description in https://docs.google.com/document/d/1JaPOKq-yHjJL3cBdmVcj8yh3RGAVt-4vq9F9C4mJ8gI/edit#bookmark=id.v8fygaoi6bij

**Comment by connerbw** [comment]
Tested with

```
<math>
  <apply>
    <eq/>
    <apply>
        <plus/>
        <apply>
            <power/>
            <ci>x</ci>
            <cn>2</cn>
        </apply>
        <apply>
            <times/>
            <cn>4</cn>
            <ci>x</ci>
        </apply>
       <cn>4</cn>
    </apply>
    <cn>0</cn>
  </apply>
</math>
```

From: https://www.w3.org/Math/whatIsMathML.html

And it worked for me.

**Comment by mcgratay** [comment]
Fine in EPUB and MOBI, but still giving me errors in PDF. 
![Screen Shot 2019-06-26 at 2 16 41 PM](https://user-images.githubusercontent.com/39064028/60204587-27294380-981d-11e9-8e5d-6dab9b4fb93a.png)

**Comment by mcgratay** [comment]
Resolved.
